#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bash ~/.config/polybar/shapes/launch.sh

bspc query -M --names
bspc monitor HDMI-0 -d I III V VII IX
bspc monitor DP-0 -d II IV VI VII X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a lunarclient desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a spotify desktop='10'
